Modifications to correct code, validate, and test code and validation…
VirtualPhotonics/VTS pull request #50
Opened 2022-09-29 19:30 UTC by hayakawa16

… for bug that disallows user to specify pMCDiffuseTransmittance database.

2022-09-29 20:35 UTC, lmalenfant commented on src/Vts.Test/MonteCarlo/DataStructuresValidation/TissueInputs/MultConcentricInfiniteCylinderTissueInputValidationTests.cs
> +    {
Hi Carole,
The Class name does not match the filename, there is an 'i' missing in the filename.

2022-09-29 20:38 UTC, lmalenfant requested changes
Hi Carole, 

It looks good, we should probably change that filename before we merge.

2022-09-29 21:45 UTC, lmalenfant approved these changes

2022-09-29 22:29 UTC, merged

2022-10-11 09:19 UTC, hayakawa16 commented
Hi Lisa,

Good catch!!  Yes, I'd like to fix it.  Do I just modify it and
push?  Do I need to close pull request and reopen?

Thanks for your help!
Carole


On 2022-09-29 13:38, Lisa Malenfant wrote:
> @lmalenfant requested changes on this pull request.
> 
> Hi Carole,
> 
> It looks good, we should probably change that filename before we
> merge.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
> 
> Links:
> ------
> [1]
> https://urldefense.com/v3/__https://github.com/VirtualPhotonics/VTS/pull/50*pullrequestreview-1125969223__;Iw!!CzAuKJ42GuquVTTmVmPViYEvSg!LwN_r10AUD93eG5ChbEHVZa0HIDznIh9d1kU-3kMc8MwNpZ1Bkwy1VfmKhcbSKSMSBBxzgiLxP-Qm-0tz0rDOIXG$
> [2]
> https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AGNQ7UZRZB4VX6DH5PHC6G3WAX447ANCNFSM6AAAAAAQZC2PRU__;!!CzAuKJ42GuquVTTmVmPViYEvSg!LwN_r10AUD93eG5ChbEHVZa0HIDznIh9d1kU-3kMc8MwNpZ1Bkwy1VfmKhcbSKSMSBBxzgiLxP-Qm-0tz26EYnrK$